USE [master]
GO
/****** Object:  Database [Coredb31]    Script Date: 08-09-2021 12:27:00 ******/
CREATE DATABASE [Coredb31]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Coredb31', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Coredb31.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Coredb31_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Coredb31_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Coredb31] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Coredb31].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Coredb31] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Coredb31] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Coredb31] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Coredb31] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Coredb31] SET ARITHABORT OFF 
GO
ALTER DATABASE [Coredb31] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Coredb31] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Coredb31] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Coredb31] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Coredb31] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Coredb31] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Coredb31] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Coredb31] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Coredb31] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Coredb31] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Coredb31] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Coredb31] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Coredb31] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Coredb31] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Coredb31] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Coredb31] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Coredb31] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Coredb31] SET RECOVERY FULL 
GO
ALTER DATABASE [Coredb31] SET  MULTI_USER 
GO
ALTER DATABASE [Coredb31] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Coredb31] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Coredb31] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Coredb31] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Coredb31] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Coredb31] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Coredb31', N'ON'
GO
ALTER DATABASE [Coredb31] SET QUERY_STORE = OFF
GO
USE [Coredb31]
GO
/****** Object:  Table [dbo].[Departments]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Departments](
	[DeptId] [int] IDENTITY(1,1) NOT NULL,
	[DeptName] [nvarchar](20) NOT NULL,
	[Location] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DeptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[EmpId] [int] IDENTITY(1,1) NOT NULL,
	[DeptId] [int] NOT NULL,
	[Designation] [nvarchar](20) NOT NULL,
	[UserId] [varchar](50) NOT NULL,
 CONSTRAINT [pk_employeeeid] PRIMARY KEY CLUSTERED 
(
	[EmpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RegisterdUsers]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegisterdUsers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [varchar](50) NOT NULL,
	[RoleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Trainees]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trainees](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[TrainingId] [int] NOT NULL,
	[EmpId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Trainings]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trainings](
	[TrainingId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](100) NOT NULL,
	[Descriptions] [nvarchar](max) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TrainingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 08-09-2021 12:27:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [varchar](50) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Phone] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [fk_DepartmentsDeptId] FOREIGN KEY([DeptId])
REFERENCES [dbo].[Departments] ([DeptId])
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [fk_DepartmentsDeptId]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [fk_UsersUserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [fk_UsersUserId]
GO
ALTER TABLE [dbo].[RegisterdUsers]  WITH CHECK ADD  CONSTRAINT [fk_RoleRegisteredUser] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([Id])
GO
ALTER TABLE [dbo].[RegisterdUsers] CHECK CONSTRAINT [fk_RoleRegisteredUser]
GO
ALTER TABLE [dbo].[RegisterdUsers]  WITH CHECK ADD  CONSTRAINT [fk_UserRegisteredUser] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[RegisterdUsers] CHECK CONSTRAINT [fk_UserRegisteredUser]
GO
ALTER TABLE [dbo].[Trainees]  WITH CHECK ADD  CONSTRAINT [fk_TrainingsTid] FOREIGN KEY([TrainingId])
REFERENCES [dbo].[Trainings] ([TrainingId])
GO
ALTER TABLE [dbo].[Trainees] CHECK CONSTRAINT [fk_TrainingsTid]
GO
ALTER TABLE [dbo].[Trainees]  WITH CHECK ADD  CONSTRAINT [fk_TrainingsUserId] FOREIGN KEY([EmpId])
REFERENCES [dbo].[Employees] ([EmpId])
GO
ALTER TABLE [dbo].[Trainees] CHECK CONSTRAINT [fk_TrainingsUserId]
GO
USE [master]
GO
ALTER DATABASE [Coredb31] SET  READ_WRITE 
GO
